spin_manifest_version = 2

[application]
name = "jillipedia"
version = "0.1.0"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "Find Mickey Episodes Fast"

[[trigger.http]]
route = "/..."
component = "jillipedia"

[component.jillipedia]
source = "main.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.jillipedia.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
