spin_manifest_version = 2

[application]
name = "jillipedia"
version = "0.1.0"
authors = ["Jason Washburn <jason.washburn@gmail.com>"]
description = "Find Mickey Episodes Fast"

[[trigger.http]]
route = "/..."
component = "jillipedia"

[component.jillipedia]
source = "main.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.jillipedia.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "static", destination = "/" }]

[[trigger.http]]
route = "/static/..."
component = "static"
